# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "list"

steps:
  Clone:
    title: Running docker image
    type: git-clone
    arguments:
      repo: 'georgeHall/packer-rest-docker'
      git: github
      revision: 'develop'


  list:
    title: "LIST"
    type: freestyle
    image: 'quay.io/codefreshplugins/alpine:3.8'
    arguments:
      image: 'quay.io/codefreshplugins/alpine:3.8'
      commands: 
       - pwd
       - ls -la
       - cat ./packer-rest-docker/codefresh.yml

  Freestyle:
    title: Running env
    type: freestyle
    working_directory: '/'
    arguments:
      image: 'quay.io/codefreshplugins/alpine:3.8'
      commands:
        - env